version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - '7001:3001'
    environment:
      NODE_ENV: production

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - '7000:3000'
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://backend:3001
    depends_on:
      - backend
