version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - '4001:3001'
    environment:
      NODE_ENV: production
    env_file:
      - apps/backend/.env

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - '4000:3000'
    environment:
      NODE_ENV: production
    env_file:
      - apps/frontend/.env.local
    depends_on:
      - backend
