export const DUMMY_INVOICE = {
  orderNumber: 'INV-000008',
  status: 'paid',
  totalPrice: 1328.58,
  orderDay: '29 Aug 2025',
  orderItems: [
    {
      productName: 'Incredible Rubber Ball',
      quantity: 1,
      price: 223.05,
      totalPrice: 223.05,
      sku: 'SKU-INV-0004',
      description: 'Discover the gray new Keyboard with an exciting mix of Marble ingredients',
      category: 'Shoes',
    },
    {
      productName: 'Elegant Wooden Chair',
      quantity: 2,
      price: 150.0,
      totalPrice: 300.0,
      sku: 'SKU-INV-0005',
      description: 'A sturdy yet stylish wooden chair with a natural finish.',
      category: 'Furniture',
    },
    {
      productName: 'Modern Steel Watch',
      quantity: 1,
      price: 175.5,
      totalPrice: 175.5,
      sku: 'SKU-INV-0006',
      description: 'Water-resistant wristwatch with stainless steel casing.',
      category: 'Accessories',
    },
    {
      productName: 'Wireless Bluetooth Headphones',
      quantity: 1,
      price: 210.0,
      totalPrice: 210.0,
      sku: 'SKU-INV-0007',
      description: 'Noise-cancelling headphones with long battery life.',
      category: 'Electronics',
    },
    {
      productName: 'Premium Leather Wallet',
      quantity: 3,
      price: 65.0,
      totalPrice: 195.0,
      sku: 'SKU-INV-0008',
      description: 'Handcrafted genuine leather wallet with multiple card slots.',
      category: 'Fashion',
    },
    {
      productName: 'Ergonomic Office Desk',
      quantity: 1,
      price: 225.03,
      totalPrice: 225.03,
      sku: 'SKU-INV-0009',
      description: 'Spacious adjustable desk designed for comfort and productivity.',
      category: 'Furniture',
    },
  ],
};
